int fast=300;
int med=800;
int slow=1100;

void Chorus() { //This is 36sec already//
	displayCenteredTextLine(0, "Kahit");sleep(fast);
	displayCenteredTextLine(1, "2v5");sleep(med+fast);
	displayCenteredTextLine(2, "basta");sleep(med+150);
	displayCenteredTextLine(3, "kasama");sleep(med);
	displayCenteredTextLine(4, "ka");sleep(med);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(0, "laging");sleep(med);
	displayCenteredBigTextLine(3, "wipeout");sleep(med);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(0, "katapat");sleep(med);
	displayCenteredBigTextLine(3, "niyan");sleep(slow);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredTextLine(0, "Kahit");sleep(med);
	displayCenteredTextLine(1, "mga");sleep(med);
	displayCenteredTextLine(2, "kills");sleep(med);
	displayCenteredTextLine(3, "ko'y");sleep(fast);
	displayCenteredTextLine(4, "puro");sleep(fast);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(1, "KS");sleep(fast);
	displayCenteredBigTextLine(3, "lang");sleep(fast+slow);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(1,"Panalo");sleep(slow);
	displayCenteredBigTextLine(3, "na");sleep(fast);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(1, "sa");sleep(fast);
	displayCenteredBigTextLine(3,"huli");sleep(med);

	displayCenteredBigTextLine(1,"Sinabi");sleep(med);
	displayCenteredBigTextLine(3,"ng");sleep(med);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(2,"OM");sleep(fast);
	displayCenteredBigTextLine(2,"");
	displayCenteredBigTextLine(1,"Bat");sleep(med);
	displayCenteredBigTextLine(3,"walang");sleep(slow);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(2,"pumunta");sleep(fast);
	displayCenteredBigTextLine(2,"");
	displayCenteredBigTextLine(1,"Di");sleep(fast);
	displayCenteredBigTextLine(3,"marunong");sleep(fast);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredTextLine(0,"ang");sleep(fast);
	displayCenteredTextLine(2, "mga");sleep(fast);
	displayCenteredTextLine(4,"yan");sleep(med);
	displayClearTextLine(0);displayClearTextLine(2);displayClearTextLine(4);
	displayCenteredTextLine(0,"Tara");sleep(med);
	displayCenteredTextLine(1,"na't");sleep(fast);
	displayCenteredTextLine(2,"patayin");sleep(med);
	displayCenteredTextLine(3,"natin");sleep(fast);
	displayCenteredTextLine(4,"ang");sleep(med);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(2,"Roshan");sleep(slow);
	displayCenteredBigTextLine(2,"");
	displayCenteredBigTextLine(1,"Panalo");sleep(slow);
	displayCenteredBigTextLine(3, "na");sleep(fast);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(1, "sa");sleep(fast);
	displayCenteredBigTextLine(3,"huli");sleep(med);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
}


task main()
{
	int oras=5;
	repeatUntil (oras==0) {
		displayCenteredBigTextLine (2, "%d", oras);
		sleep(1000);
		oras=oras-1;
	}
	displayCenteredBigTextLine (2, "");
	displayCenteredTextLine(0,"Ang");sleep(fast-100);
	displayCenteredTextLine(1,"ping");sleep(fast);
	displayCenteredTextLine(2,"mo");sleep(fast);
	displayCenteredTextLine(3,"ay");sleep(fast);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);
	displayCenteredBigTextLine(0,"taas");sleep(med);
	displayCenteredBigTextLine(3,"baba");sleep(med);
	sleep(1000);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredTextLine(0,"Kakampi");sleep(med);
	displayCenteredTextLine(1,"mo'y");sleep(fast);
	displayCenteredTextLine(2,"mga");sleep(fast+150);
	displayCenteredTextLine(3,"bano");sleep(med);
	displayCenteredTextLine(4,"pa");sleep(med);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredTextLine(0,"wag");sleep(fast);
	displayCenteredTextLine(1,"ka");sleep(fast);
	displayCenteredTextLine(2,"muna");sleep(fast);
	displayCenteredTextLine(3,"mag");sleep(fast);
	displayCenteredTextLine(4,"quit");sleep(med);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(0,"Panalo");sleep(slow);
	displayCenteredBigTextLine(3,"na");sleep(fast-150);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(0,"sa");sleep(fast-150);
	displayCenteredBigTextLine(3,"Huli");sleep(med);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	sleep(med);
	displayCenteredBigTextLine(0,"Mga");sleep(fast);
	displayCenteredBigTextLine(3,"tore'y");sleep(fast);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(0,"nasira");sleep(med);
	displayCenteredBigTextLine(3,"na");sleep(med+slow);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(1,"Nais");sleep(fast);
	displayCenteredBigTextLine(1,"");
	displayCenteredTextLine(0,"ko");sleep(fast);
	displayCenteredTextLine(1,"lang");sleep(fast);
	displayCenteredTextLine(2,"ang");sleep(med);
	displayCenteredTextLine(3,"patayin");sleep(med);
	displayCenteredTextLine(4,"sila");sleep(med+fast);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredTextLine(0,"Wag");sleep(fast);
	displayCenteredTextLine(1,"ka");sleep(fast);
	displayCenteredTextLine(2,"muna");sleep(fast);
	displayCenteredTextLine(3,"mag");sleep(fast);
	displayCenteredTextLine(4,"quit");sleep(fast+med);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(0,"Panalo");sleep(slow);
	displayCenteredBigTextLine(3,"na");sleep(fast-150);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(0,"sa");sleep(fast-150);
	displayCenteredBigTextLine(3,"huli");sleep(med);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	Chorus();//1:06 here
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredTextLine(0,"Blink");sleep(fast);
	displayCenteredTextLine(1,"in");sleep(fast);
	displayCenteredTextLine(2,"sabay");sleep(fast);
	displayCenteredTextLine(3,"SS");sleep(slow);
	displayCenteredTextLine(4,"agad");sleep(med);
	sleep(1000);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredTextLine(0,"Tingin");sleep(fast);
	displayCenteredTextLine(1,"pero");sleep(fast);
	displayCenteredTextLine(2,"walang");sleep(fast);
	displayCenteredTextLine(3,"follow");sleep(med);
	displayCenteredTextLine(4,"up");sleep(med);
	sleep(1000);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(0,"Ako'y");sleep(fast-150);
	displayCenteredBigTextLine(3,"naiinis");sleep(slow+500);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(0,"Panalo");sleep(slow);
	displayCenteredBigTextLine(3,"na");sleep(fast-150);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(0,"sa");sleep(fast-150);
	displayCenteredBigTextLine(3,"huli");sleep(med);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredTextLine(1,"Mid");sleep(fast);
	displayCenteredTextLine(2,"na");sleep(fast);
	displayCenteredTextLine(3,"AFK");sleep(fast);
	displayCenteredTextLine(4,"muli");sleep(fast);
	sleep(1000);
	displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(0,"(AFK");sleep(fast);
	displayCenteredBigTextLine(3,"muli)");sleep(slow-150);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredTextLine(1,"Kalaban");sleep(fast);
	displayCenteredTextLine(2,"mo'y");sleep(fast);
	displayCenteredTextLine(3,"nagwawagi");sleep(med);
	sleep(1000);
	displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);
	displayCenteredTextLine(1,"Puro");sleep(fast);
	displayCenteredTextLine(2,"feeder");sleep(fast);
	displayCenteredTextLine(3,"kampi");sleep(med);
	sleep(1000);
	displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);
	displayCenteredBigTextLine(0,"Panalo");sleep(slow);
	displayCenteredBigTextLine(3,"na");sleep(fast-150);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(0,"sa");sleep(fast-150);
	displayCenteredBigTextLine(3,"huli");sleep(med);
	displayCenteredBigTextLine(0,"");displayCenteredBigTextLine(3,"");
	Chorus();
	displayCenteredTextLine(0,"Mga");sleep(med);
	displayCenteredTextLine(1,"kakampi");sleep(med);
	displayCenteredTextLine(2,"mong");sleep(fast);
	displayCenteredTextLine(3,"walang");sleep(med);
	displayCenteredTextLine(4,"mga");sleep(fast);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredBigTextLine(2,"skill");sleep(fast);
	sleep(1000);
	displayCenteredBigTextLine(2,"");
	displayCenteredTextLine(1,"Palagi");sleep(med);
	displayCenteredTextLine(2,"kang");sleep(fast);
	displayCenteredTextLine(3,"hinahanap");sleep(med);
	sleep(1000);
	displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);
	displayCenteredTextLine(1,"Nagpapabuhat");sleep(med);
	displayCenteredTextLine(2,"na");sleep(fast);
	displayCenteredTextLine(3,"lang");sleep(fast);
	sleep(1000);
	displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);
	displayCenteredTextLine(1,"Di");sleep(fast);
	displayCenteredTextLine(2,"ka");sleep(med);
	displayCenteredTextLine(3,"maka");sleep(fast);
	displayCenteredTextLine(4,"hindi");sleep(slow);
	displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	displayCenteredTextLine(1,"Sa");sleep(fast);
	displayCenteredTextLine(2,"tuwing");sleep(med);
	displayCenteredTextLine(3,"ika'y");sleep(fast);
	displayCenteredTextLine(4,"isasali");sleep(slow);
	displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);displayClearTextLine(4);
	oras=5;
	repeatUntil (oras==0) {
		displayCenteredBigTextLine (2, "%d", oras);
		sleep(1000);
		oras=oras-1;
	}
	Chorus();
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(1,"Panalo");sleep(slow);
	displayCenteredBigTextLine(3, "na");sleep(fast);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredBigTextLine(1, "sa");sleep(fast);
	displayCenteredBigTextLine(3,"huli");sleep(med);
	displayCenteredBigTextLine(1,"");displayCenteredBigTextLine(3,"");
	displayCenteredTextLine(0,"Panalo");sleep(2*slow);
	displayCenteredTextLine(1, "na");sleep(fast);
	displayCenteredTextLine(2, "sa");sleep(fast);
	displayCenteredTextLine(3,"huli");sleep(2*med);
	displayClearTextLine(0);displayClearTextLine(1);displayClearTextLine(2);displayClearTextLine(3);
	displayCenteredTextLine(4, "fin");sleep(999999);

}
